// What each token is, for the Token Kit's list and stat block: a readable name, its set, its
// footprint, a kind (a sorting label, not a rules ruling: the GM decides what a token counts as) and
// notes. Matched by name, first rule that fits.

export const SETS = {
  kit: { name: "Ship kit", colour: "#7db6e8" },
  milbay: { name: "Military Bay", colour: "#d98d2a" },
  vr: { name: "V-Reality", colour: "#b07ce0" },
  training: { name: "Training Floor", colour: "#e8743f" },
  depot: { name: "Depot", colour: "#4fa3bf" },
  annex: { name: "Generator Annex", colour: "#5cbf6a" },
  silos: { name: "Ballistic Silos", colour: "#6f86d8" },
};

const RULES = [
  [/^wall$/, "Wall", "Wall", "Plated ship wall. Delete it when the wall is destroyed; drop a breached wall where it was holed."],
  [/^wall_breached$/, "Breached wall", "Wall", "A holed section of wall: torn plating and debris."],
  [/^door$/, "Door", "Wall", "A hazard-striped blast door."],
  [/^cover_hard_size(\d)$/, "Hard cover marker", "Cover", "A plain marker; the number is its Size."],
  [/^cover_soft$/, "Soft cover (smoke)", "Cover", "Smoke puffs inside a dashed rim."],
  [/^elevated_\+(\d)$/, "Raised ground +$1 (old)", "Raised ground", "The first raised-ground tiles, with the height printed on. Superseded by deck plates and sim ground with height markers."],
  [/^height_\+(\d)$/, "Height marker +$1", "Marker", "Just the \"+N\", at the upper right of the hex, outlined so it reads on any floor. Put one on raised ground."],
  [/^coolant$/, "Coolant pool", "Hazard", "Blue coolant with ripples."],
  [/^ladder$/, "Ladder", "Prop", ""],
  [/^rubble_difficult$/, "Rubble", "Difficult terrain", "Loose rubble, clipped to the hex."],
  [/^rock_obstruction$/, "Rock", "Obstruction", "Dark cracked stone."],
  [/^hazard_dangerous$/, "Hazard", "Hazard", "A red hex with a warning triangle."],
  [/^reactor_core$/, "Reactor core", "Objective", ""],
  [/^reactor_core_armor$/, "Core plating", "Wall", "Reactor containment: a stepped inner plate, hex bolts and a trefoil, heat-tinted rim."],
  [/^turret$/, "Turret", "Prop", ""],
  [/^relay_size2$/, "Relay dish", "Objective", "A comms relay across three hexes."],
  [/^forklift_size2$/, "Cargo loader", "Cover", "A forklift with forks up into the top hex, carrying a crate."],
  [/^hatch$/, "Hatch (closed)", "Prop", "A floor hatch with a hand wheel."],
  [/^hatch_open$/, "Hatch (open)", "Prop", "An open floor hatch with a ladder going down."],
  [/^terminal$/, "Terminal", "Prop", "A console with a lit screen."],
  [/^pipes$/, "Pipes", "Prop", "Two pipes running east-west; tiles with the next hex along a row."],
  [/^bomb$/, "Bomb", "Objective", "An olive-drab bomb on a skid cradle, nose east, yellow HE bands and a red arming lamp. An escort objective."],
  [/^blast_area_(\d)$/, "Blast $1 area", "Marker", "A half-transparent explosion covering exactly a Blast $1 (centre the token on the target hex). Lay it over the map where a bombardment, mine or grenade goes off."],
  [/^drop_pod_size3$/, "Drop pod", "Prop", "A boring drop pod, drill head pointing east."],
  [/^crate_v(\d)$/, "Crate", "Cover", "Wood, steel or blue crates; the steel ones carry stencils."],
  [/^crate_stack_v(\d)$/, "Crate stack", "Cover", "A small crate stacked on a big one."],
  [/^crate_pile_size2_v(\d)$/, "Crate pile", "Cover", "Three or four crates huddled over three hexes, one stacked on top."],
  [/^container_2hex_v(\d)$/, "Cargo container", "Cover", "A stencilled container across two hexes side by side."],
  [/^barrels_v(\d)$/, "Barrels", "Cover", ""],
  [/^sandbags_v(\d)$/, "Sandbag wall", "Cover", "Runs east-west across the hex, whole bags at the ends, so neighbours overlap naturally. Rotate in 60° steps for other directions."],
  [/^sandbag_nest_v(\d)$/, "Sandbag nest", "Cover", "A curved gun position, open to the south."],
  [/^tank_trap_hedgehog_v(\d)$/, "Tank trap (hedgehog)", "Cover", "Steel 'Czech hedgehogs': one big, or a cluster of three."],
  [/^tank_trap_tetrapod_v(\d)$/, "Tank trap (tetrapod)", "Cover", "Concrete tetrapods: one big, or two."],
  [/^barbed_wire_v(\d)$/, "Barbed wire", "Prop", "A concertina coil east-west through the hex; joins with its neighbours."],
  [/^mb_deck_edge2$/, "Deck plate, corner edge", "Raised ground", "A steel deck plate with hazard stripes on two edges where the deck drops away. Rotate in 60° steps to face the drop."],
  [/^mb_deck_edge$/, "Deck plate, edge", "Raised ground", "A steel deck plate with hazard stripes on the edge where the deck drops away. Rotate in 60° steps to face the drop."],
  [/^mb_deck_v(\d)$/, "Deck plate", "Raised ground", "One hex of raised tread-plate deck; neighbouring plates read as one deck. Heights go on height markers."],
  [/^mb_barrier_2hex$/, "Concrete barrier (long)", "Cover", "A chipped jersey barrier across two hexes, two rebar loops."],
  [/^mb_barrier_v(\d)$/, "Concrete barrier", "Cover", "A jersey barrier with a rebar lifting loop."],
  [/^mb_shells_v(\d)$/, "Artillery shells", "Prop", "Standing shells, red-orange caps."],
  [/^mb_munitions_pallet$/, "Munitions pallet", "Prop", "Warheads lying in rows on a pallet."],
  [/^mb_ammo_cage$/, "Ammo cage", "Prop", "A steel cage packed with canisters, blue label strip."],
  [/^mb_gas_tanks$/, "Gas tanks", "Prop", "Two pale gas tanks and small coloured bottles."],
  [/^mb_generator$/, "Generator", "Prop", "A grey unit with vents, a hazard corner and an indicator light."],
  [/^mb_rocket_stack$/, "Rocket stack", "Prop", "Long orange rockets on a pallet, across two hexes."],
  [/^mb_anchor_v(\d)$/, "Floor anchor", "Prop", "A Y-shaped floor anchor. Decoration, not cover."],
  [/^vr_ground_destroyed_v(\d)$/, "Sim ground, shattered", "Raised ground", "Destroyed basalt: cracked from a point of impact, columns knocked out to the void, rubble, de-rezzing pixels."],
  [/^vr_ground_v(\d)$/, "Sim ground (basalt)", "Raised ground", "Basalt column tops; the tiling lines up across neighbouring tokens, so a plateau reads as one surface."],
  [/^vr_sand_v(\d)$/, "Sim ground (sand)", "Raised ground", "A lilac sand mound with crystal grit."],
  [/^vr_spawn_pad$/, "Spawn pad", "Objective", "A green teleporter pad. Goes on top of the ground."],
  [/^vr_flag_stand$/, "Flag stand", "Objective", "Goes on top of the ground."],
  [/^vr_flag$/, "Flag", "Objective", "The flag itself, to carry around."],
  [/^vr_pillar_size2$/, "Basalt pillars", "Cover", "Three big hex pillars across three hexes."],
  [/^vr_pillar_size1_v(\d)$/, "Basalt pillar", "Cover", "One big hex pillar: chipped, cracked or sheared."],
  [/^vr_basalt_size(\d)$/, "Basalt columns", "Cover", "Hex columns packed into the footprint."],
  [/^vr_boulder_size2$/, "Boulder (large)", "Cover", "A faceted boulder across three hexes, with violet crystal glints."],
  [/^vr_boulder_size1_v(\d)$/, "Boulder", "Cover", "A faceted boulder with violet crystal glints."],
  [/^tf_cylinders_v(\d)$/, "Gas cylinders", "Cover", "Two to four standing gas cylinders, mostly orange, sometimes a grey one."],
  [/^tf_tarp_stack_camo_v(\d)$/, "Tarp stack, camo-netted", "Cover", "A crate stack under a dark tarp, with camouflage netting over the top."],
  [/^tf_tarp_stack_v(\d)$/, "Tarp stack", "Cover", "A crate stack under a dark tarp that spreads onto the ground."],
  [/^tf_dragon_tooth$/, "Dragon's tooth", "Cover", "A truncated concrete pyramid (anti-vehicle obstacle)."],
  [/^tf_posts_v(\d)$/, "Concrete posts", "Cover", "Pointed hexagonal concrete posts: three, or two."],
  [/^tf_concrete_block$/, "Concrete block", "Cover", "A big cast block with a lifting hole."],
  [/^tf_panel_stack$/, "Concrete panel stack", "Cover", "Four long panels strapped on a pallet."],
  [/^tf_radar_dish_size2$/, "Radar dish", "Objective", "A big dish on a toothed mount, on a concrete base. Across three hexes."],
  [/^tf_pipe_rack_2hex$/, "Pipe rack", "Cover", "Yellow pipes lying east-west in black truss frames, across two hexes."],
  [/^tf_fence$/, "Palisade fence", "Wall", "Black spear-top fence running east-west; tiles along a row. Rotate in 60° steps for other directions."],
  [/^tf_tyres_v(\d)$/, "Tyre stacks", "Cover", "Stacks of truck tyres."],
  [/^tf_wheel$/, "Big wheel", "Cover", "One big vehicle wheel lying flat, yellow hub."],
  [/^tf_pallet$/, "Pallet", "Prop", "An empty wooden pallet."],
  [/^tf_wpn_crate$/, "WPN crate", "Objective", "The blue weapons crate. A loot drop, or something to recover."],
  [/^tf_supplies$/, "Supply boxes", "Cover", "White supply boxes of mixed sizes on a pallet."],
  [/^tf_tent_2hex$/, "Tent", "Cover", "A long white tent in two sections, across two hexes."],
  [/^tf_apc_size2$/, "APC under camo net", "Cover", "A parked armoured carrier with camouflage netting over it. Across three hexes."],
  [/^dp_tank_size2_v(\d)$/, "Storage tank", "Cover", "A squat steel-blue tank with a railing ring on top, gas bottles or a drum at its foot. Across three hexes."],
  [/^dp_tank_tall_size2$/, "Tall tank", "Cover", "A tall stencilled tank with a riser pipe up its side. Across three hexes."],
  [/^dp_tank_lying_3hex$/, "Lying tank", "Cover", "A long tank lying east-west on saddles, a catwalk on top, gas bottles in front. Three hexes in a row."],
  [/^dp_bottles_v(\d)$/, "Gas bottles", "Cover", "Two to four standing gas bottles with caps, collars and yellow valve guards."],
  [/^dp_drums_v(\d)$/, "Steel drums", "Cover", "Two or three ribbed steel drums."],
  [/^dp_crate_v1$/, "Wooden crate", "Cover", "One braced wooden crate."],
  [/^dp_crate_v2$/, "Wooden crates", "Cover", "Two braced wooden crates, staggered."],
  [/^dp_crate_v3$/, "Tall crate", "Cover", "A long wooden crate standing north-south."],
  [/^dp_crate_stack$/, "Crate pair", "Cover", "Two tall wooden crates with a gas bottle in front."],
  [/^dp_ammo_crate$/, "Ammo crate", "Objective", "The yellow AMMO crate. A loot drop, or something to recover."],
  [/^dp_supplies_v(\d)$/, "Supply boxes", "Cover", "White boxes of mixed sizes strapped on a pallet."],
  [/^dp_block_pallet$/, "Concrete blocks", "Cover", "A pallet of grey concrete cubes."],
  [/^dp_hollow_block$/, "Hollow block", "Cover", "A cast concrete block with a square opening, long north-south. Line several up for a low wall."],
  [/^dp_pipe_bundle_size2$/, "Pipe bundle", "Cover", "Eight big flanged pipes stacked 3-2-3, open ends to the south. Across three hexes."],
  [/^dp_pipe_stack_2hex$/, "Pipe stack", "Cover", "Dark pipes with yellow bands, lying east-west in black frames. Two hexes."],
  [/^dp_u_pipe_3hex$/, "U-pipe", "Cover", "A galvanised pipe on the floor whose ends bend down into flange plates. Three hexes in a row."],
  [/^dp_tetrapod_v(\d)$/, "Tetrapod", "Cover", "A three-legged concrete obstacle with one arm standing up."],
  [/^dp_dragon_tooth_v(\d)$/, "Dragon's tooth (grey)", "Cover", "A cool grey concrete frustum (anti-vehicle obstacle), for the floors after the Training Floor."],
  [/^dp_sheet_wall$/, "Sheet piling", "Wall", "Dark corrugated steel wall running east-west; tiles along a row. Rotate in 60° steps for other directions."],
  [/^dp_railing$/, "Railing", "Wall", "A steel railing running east-west, for trench and platform edges; tiles along a row."],
  [/^dp_container_3hex$/, "Container", "Cover", "A dark container with a ribbed roof and a worn orange band. Three hexes in a row."],
  [/^dp_slabs_2hex$/, "Steel slabs", "Cover", "Stacked steel slabs with holes and end pegs, strapped. Two hexes."],
  [/^ga_transformer_size2$/, "Transformer", "Cover", "A dark transformer with six yellow insulators leaning outward. Across three hexes."],
  [/^ga_generator_size2$/, "Generator block", "Cover", "A tall dark ribbed generator with a bolted top panel. Across three hexes."],
  [/^ga_fan_unit$/, "Fan unit", "Cover", "A dark block with a round fan on top."],
  [/^ga_battery_rack_2hex$/, "Battery rack", "Cover", "A grey-green cabinet with a grid of battery cells on top. Two hexes."],
  [/^ga_power_cabinet_3hex$/, "Power cabinet", "Cover", "A yellow-framed cabinet with three big fans in its deck. Three hexes in a row."],
  [/^ga_vent_box$/, "Vent box", "Cover", "A dark radiator block with slats on top."],
  [/^ga_barrier_v(\d)$/, "Broken barrier", "Cover", "A chipped concrete barrier stub with rebar at the break."],
  [/^ga_railing$/, "Green railing", "Wall", "The Annex's green railing, running east-west; tiles along a row."],
  [/^ga_upg_crate$/, "UPG crate", "Objective", "The upgrade crate with its yellow sticker. A loot drop, or something to recover."],
  [/^bs_missile_size2$/, "Missile in its rack", "Objective", "A black missile nose cone standing in a blue braced launch rack. Across three hexes."],
  [/^bs_silo_size2_v1$/, "Capped silo", "Cover", "A silo mouth capped with a ring of red bolts, in a blue rack. Across three hexes."],
  [/^bs_silo_size2_v2$/, "Open silo", "Cover", "An open silo mouth, a dark shaft in a blue rack. Across three hexes."],
  [/^bs_tank_rack_3hex$/, "Tank in a cage", "Cover", "A blue tank lying east-west in a braced scaffold cage, red at one end. Three hexes in a row."],
  [/^bs_tank_cage_size2$/, "Tall tank in a cage", "Cover", "A tall blue tank with a red arc on its dome, in a scaffold cage. Across three hexes."],
  [/^bs_lid_size2$/, "Silo lid", "Cover", "A big closed blue silo lid with a hinge and bolts. Across three hexes."],
  [/^bs_bottles_v(\d)$/, "Blue gas bottles", "Cover", "Three or four blue gas bottles."],
  [/^bs_drums_v(\d)$/, "Blue drums", "Cover", "Two or three blue steel drums."],
  [/^bs_container_3hex$/, "Navy container", "Cover", "A dark navy container with a worn orange band. Three hexes in a row."],
  [/^bs_railing$/, "Blue railing", "Wall", "The Silos' blue railing, running east-west; tiles along a row."],
];

export function describe(name) {
  const set = name.startsWith("mb_") ? "milbay" : name.startsWith("vr_") ? "vr" : name.startsWith("tf_") ? "training" : name.startsWith("dp_") ? "depot" : name.startsWith("ga_") ? "annex" : name.startsWith("bs_") ? "silos" : "kit";
  let title = name, kind = "Prop", notes = "";
  for (const [re, t, k, n] of RULES) {
    const m = name.match(re);
    if (!m) continue;
    title = t.replace("$1", m[1]);
    kind = k;
    notes = n;
    break;
  }
  const v = name.match(/_v(\d+)$/);
  const blast = name.match(/^blast_area_(\d)$/);
  const footprint = blast ? `Blast ${blast[1]}` : /size3/.test(name) ? "Size 3" : /size2/.test(name) ? "Size 2" : /3hex/.test(name) ? "3 hexes" : /2hex|rocket_stack/.test(name) ? "2 hexes" : "Size 1";
  return { name, set, title, variant: v ? Number(v[1]) : null, kind, notes, footprint,
    family: name.replace(/_v\d+$/, "") };
}

export const FOOTPRINT_TEXT = {
  "Size 1": "one hex",
  "Size 2": "three hexes: one on top, two below",
  "Size 3": "seven hexes: one and its six neighbours",
  "2 hexes": "two hexes side by side",
  "3 hexes": "three hexes in a row, centred on the middle one",
  "Blast 1": "seven hexes: the target hex and its six neighbours",
  "Blast 2": "nineteen hexes: the target hex and two rings around it",
  "Blast 3": "thirty-seven hexes: the target hex and three rings around it",
};
